# -*- coding: utf-8 -*-
"""Lista de Exercicio.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1dm3JxHBDgUxCwUyWAl3UgZHy5N_u9zgW

QUESTÃO 12 - Faça um programa para o cálculo de uma folha de pagamento, sabendo que os descontos são do Imposto de Renda, que depende do salário bruto (conforme tabela abaixo) e 3% para o Sindicato e que o FGTS corresponde a 11% do Salário Bruto, mas não é descontado (é a empresa que deposita). O Salário Líquido corresponde ao Salário Bruto menos os descontos. O programa deverá pedir ao usuário o valor da sua hora e a quantidade de horas trabalhadas no mês.
Desconto do IR:
Salário Bruto até 900 (inclusive) - isento
Salário Bruto até 1500 (inclusive) - desconto de 5%
Salário Bruto até 2500 (inclusive) - desconto de 10%
Salário Bruto acima de 2500 - desconto de 20% Imprima na tela as informações, dispostas conforme o exemplo abaixo. No exemplo o valor da hora é 5 e a quantidade de hora é 220.
        Salário Bruto: (5 * 220)        : R$ 1100,00
        (-) IR (5%)                     : R$   55,00  
        (-) INSS ( 10%)                 : R$  110,00
        FGTS (11%)                      : R$  121,00
        Total de descontos              : R$  165,00
        Salário Liquido                 : R$  935,00
"""

print("##############FOLHA DE PAGAMENTO##################")


salario_bruto = 0
salario_liquido = 0
custo_hora = 5
horas_trabalhadas =  0
#DESCONTO

#NÃO DESCONTA A EMPRESA DEPOSITA


resposta = input("Deseja fazer o calculo de salário? \n Digite 1 para Sim e 2 para Não: ")
while resposta == '1':
    horas_trabalhadas = int(input("Informe a quantidade de horas trabalhadas: "))
    salario_bruto = horas_trabalhadas * custo_hora
    print("###########CALCULO DO SALARIO##########")
    if salario_bruto <= 900:
        print(f"Salário Bruto: {salario_bruto}")
        print('Você está isento do IR')
        salario_liquido = salario_bruto - (salario_bruto * INSS)
        print(f"O INSS é de {INSS} e o salário líquido é de {salario_liquido}")
        print(f"O FGTS a ser depositado pela empresa: {salario_bruto * FGTS}")

    elif salario_bruto <= 1500:
        IR = salario_bruto * 0.05
        INSS = salario_bruto*0.1
        FGTS = salario_bruto * 0.11
        print(f"Salário Bruto: {salario_bruto}")
        print(f'(-) IR (5%)                     : {IR}')
        print(f'(-) INSS (10%)                  : {INSS}')
        print(f"FGTS (11%)                      : {FGTS}")
        print(f"Total de descontos              : {IR + INSS}")
        print(f"Salário Liquido                 :{salario_bruto - IR - INSS}")

    elif salario_bruto <= 2500:
        IR = salario_bruto * 0.1
        INSS = salario_bruto*0.1
        FGTS = salario_bruto * 0.11
        print(f"Salário Bruto: {salario_bruto}")
        print(f'(-) IR (10%)                     : {IR}')
        print(f'(-) INSS (10%)                  : {INSS}')
        print(f"FGTS (11%)                      : {FGTS}")
        print(f"Total de descontos              : {IR + INSS}")
        print(f"Salário Liquido                 :{salario_bruto - IR - INSS}")

    else:
        IR = salario_bruto * 0.2
        INSS = salario_bruto*0.1
        FGTS = salario_bruto * 0.11
        print(f"Salário Bruto: {salario_bruto}")
        print(f'(-) IR (20%)                     : {IR}')
        print(f'(-) INSS (10%)                  : {INSS}')
        print(f"FGTS (11%)                      : {FGTS}")
        print(f"Total de descontos              : {IR + INSS}")
        print(f"Salário Liquido                 :{salario_bruto - IR - INSS}")

    resposta = input("Deseja fazer o calculo de salário? \n Digite 1 para Sim e 2 para Não: ")
print('ENCERRADO!')

"""QUESTÃO 14 - Faça um programa que lê as duas notas parciais obtidas por um aluno numa disciplina ao longo de um semestre, e calcule a sua média. A atribuição de conceitos obedece à tabela abaixo:

Média de Aproveitamento  Conceito
  Entre 9.0 e 10.0    =    A

  Entre 7.5 e 9.0     =    B

  Entre 6.0 e 7.5     =    C

  Entre 4.0 e 6.0      =   D

  Entre 4.0 e zero     =   E
"""

print("DIGITE ABAIXO AS NOTAS PARA CALCULAR A MÉDIA DO SEMESTRE: \n")
nota1 = float(input("Digite a primeira nota: "))
nota2 = float(input("Digite a segunda nota: "))
media = (nota1 + nota2)/2

if media <= 4:
    print(f"Sua media é: {media} \n" +
           "Conceito: E \n" +
           "Situação: REPROVADO")
elif media <= 6:
    print(f"Sua media é: {media} \n" +
           "Conceito: D \n" +
           "Situação: REPROVADO")
elif media <= 7.5:
    print(f"Sua media é: {media} \n" +
           "Conceito: C \n" +
           "Situação: APROVADO")
elif media <= 9:
    print(f"Sua media é: {media} \n" +
           "Conceito: B \n" +
           "Situação: APROVADO")
elif media <= 10:
    print(f"Sua media é: {media} \n" +
           "Conceito: A \n" +
           "Situação: APROVADO")

"""QUESTAO 04 - Supondo que a população de um país A seja da ordem de 80000 habitantes com uma taxa anual de crescimento de 3% e que a população de B seja 200000 habitantes com uma taxa de crescimento de 1.5%. Faça um programa que calcule e escreva o número de anos necessários para que a população do país A ultrapasse ou iguale a população do país B, mantidas as taxas de crescimento."""

def calcular_anos(populacao_a, taxa_a, populacao_b, taxa_b):
    anos = 0
    while populacao_a < populacao_b:
        populacao_a *= (1 + taxa_a / 100)
        populacao_b *= (1 + taxa_b / 100)
        anos += 1
    return anos

populacao_a = 80000
taxa_a = 3
populacao_b = 200000
taxa_b = 1.5

anos_necessarios = calcular_anos(populacao_a, taxa_a, populacao_b, taxa_b)
print("Serão necessários aproximadamente", anos_necessarios, "anos para que a população do país A ultrapasse ou iguale a população do país B.")

#POPULAÇÃO A = 80.000 e cresce 3%
#POPULAÇÃO B = 200.000 e cresce 1.5%

populacao_A = 80.000
populacao_B = 200.000
continuar = True
while continuar:
    cont = 0
    while populacao_A < populacao_B:
        populacao_A = populacao_A + (populacao_A * 0.03)
        populacao_B = populacao_B + (populacao_B * 0.015)
        cont = cont +1
    print(f"Será necessário {cont} anos para que População A seja maior ou igual a B")
    continuar = False

"""QUESTAO 33 - Departamento Estadual de Meteorologia lhe contratou para desenvolver um programa que leia as um conjunto indeterminado de temperaturas, e informe ao final a menor e a maior temperaturas informadas, bem como a média das temperaturas."""

temperaturas = []

while True:
   temperatura = input("Informe uma temperatura (ou 'fim' para encerrar): ")
   if temperatura.lower() == 'fim':
    break
   try:
    temperatura = float(temperatura)
    temperaturas.append(temperatura)
   except ValueError:
    print("Por favor, insira um valor numérico válido.")

if temperaturas:
    menor = temperaturas[0]
    maior = temperaturas [0]
    somaTemp = 0
    cont = 0

    for i in range(len(temperaturas)):
        temperatura = temperaturas[i]
        if temperatura < menor:
            menor = temperatura
        if temperatura > maior:
            maior = temperatura
        somaTemp += temperatura
        cont += 1

    media_temperatura = somaTemp / cont

    print("\nMenor temperatura:", menor)
    print("Maior temperatura:", maior)
    print("Média das temperaturas:", media_temperatura)
else:
    print("Nenhuma temperatura foi informada.")

temperaturas = []
while True:
    temperatura = input("Informe uma temperatura (ou 'fim' para encerrar): ")
    if temperatura.lower() == 'fim':
        break
    try:
        temperatura = float(temperatura)
        temperaturas.append(temperatura)
    except ValueError:
        print("Por favor, insira um valor numérico válido.")

if temperaturas:
    menor_temperatura = temperaturas[0]
    maior_temperatura = temperaturas[0]
    soma_temperaturas = 0
    contador = 0

    for i in range(len(temperaturas)):
        temperatura = temperaturas[i]
        if temperatura < menor_temperatura:
            menor_temperatura = temperatura
        if temperatura > maior_temperatura:
            maior_temperatura = temperatura
        soma_temperaturas += temperatura
        contador += 1

    media_temperatura = soma_temperaturas / contador

    print("\nMenor temperatura:", menor_temperatura)
    print("Maior temperatura:", maior_temperatura)
    print("Média das temperaturas:", media_temperatura)
else:
    print("Nenhuma temperatura foi informada.")